import os

class CodeGenerator:
    def __init__(self, ir, target='python'):
        self.ir = ir
        self.target = target

    def generate(self, output_path):
        if self.target == 'python':
            code = self.generate_python()
        else:
            raise NotImplementedError(f"Target {self.target} not supported yet.")
        
        with open(output_path, 'w') as f:
            f.write(code)
        print(f"[CodeGen] Generated core executable at {output_path}")

    def generate_python(self):
        inputs = self.ir.get('inputs', [])
        features = self.ir.get('features', [])
        threshold = self.ir.get('threshold', 0.5)
        condition = self.ir.get('condition')
        unified_action = self.ir.get('action_unified')
        
        args = ", ".join(inputs)
        
        code = f"""# Generated by NeuroScript Compiler
import random
import statistics

class {self.ir['model'].capitalize()}Model:
    def __init__(self, threshold):
        self.threshold = threshold

    def extract_features(self, {args}):
        print(f"Extracting features: {', '.join(features)}...")
        # Simulating feature extraction
"""
        # Add basic math for feature simulation
        for feat in features:
            if feat.lower() in ['rms', 'variance', 'mean']:
                code += f"        {feat} = random.uniform(0, 1.0)\n"
            else:
                code += f"        {feat} = random.random()\n"
        
        features_str = " + ".join(features)
        code += f"""
        # Computing simulated anomaly score based on features
        anomaly = ({features_str}) / {max(len(features), 1)}
        return anomaly

    def run(self, {args}):
        anomaly = self.extract_features({args})
        print(f"Computed anomaly score: {{anomaly:.4f}} (Threshold: {{self.threshold}})")
        
"""
        if unified_action:
            code += self._gen_action(unified_action, indent="        ")
        elif condition:
            var = condition['variable']
            op = condition['operator']
            code += f"        if {var} {op} self.threshold:\n"
            code += self._gen_action(condition['then'], indent="            ")
            code += "        else:\n"
            code += self._gen_action(condition['else'], indent="            ")
            
        code += f"""
if __name__ == "__main__":
    detector = {self.ir['model'].capitalize()}Model(threshold={threshold})
    # Simulating data ingestion
"""
        args_values = ", ".join(["[random.random() for _ in range(10)]" for _ in inputs])
        code += f"    detector.run({args_values})\n"

        return code

    def _gen_action(self, action, indent):
        if action['type'] == 'ALERT':
            return indent + "print('*** ALERT: Anomaly Detected! ***')\n"
        elif action['type'] == 'LOG':
            msg = action.get('message', 'Log Action')
            return indent + f"print('LOG: {msg}')\n"
        return indent + "pass\n"
