
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALERT COMMA ELSE EQ EXTRACT FEATURE GT IDENTIFIER IF INPUT LOG LT MODEL NUMBER R_MODEL R_THRESHOLD STRING_LITERAL THEN THRESHOLD TRAIN USINGprogram : model_decl input_decl feature_decl train_decl condition_declmodel_decl : MODEL IDENTIFIERinput_decl : INPUT ident_listfeature_decl : FEATURE EXTRACT ident_listtrain_decl : TRAIN R_MODEL USING R_THRESHOLD NUMBERcondition_decl : IF IDENTIFIER GT THRESHOLD THEN action ELSE action\n| IF IDENTIFIER LT THRESHOLD THEN action ELSE action\n| IF IDENTIFIER EQ THRESHOLD THEN action ELSE actionaction : ALERT\n| LOG STRING_LITERALident_list : IDENTIFIERident_list : IDENTIFIER COMMA ident_list'
    
_lr_action_items = {'MODEL':([0,],[3,]),'$end':([1,15,34,39,42,43,44,],[0,-1,-9,-10,-6,-7,-8,]),'INPUT':([2,6,],[5,-2,]),'IDENTIFIER':([3,5,13,14,16,],[6,10,10,10,20,]),'FEATURE':([4,9,10,19,],[8,-3,-11,-12,]),'TRAIN':([7,10,18,19,],[12,-11,-4,-12,]),'EXTRACT':([8,],[13,]),'COMMA':([10,],[14,]),'IF':([11,29,],[16,-5,]),'R_MODEL':([12,],[17,]),'USING':([17,],[21,]),'GT':([20,],[22,]),'LT':([20,],[23,]),'EQ':([20,],[24,]),'R_THRESHOLD':([21,],[25,]),'THRESHOLD':([22,23,24,],[26,27,28,]),'NUMBER':([25,],[29,]),'THEN':([26,27,28,],[30,31,32,]),'ALERT':([30,31,32,38,40,41,],[34,34,34,34,34,34,]),'LOG':([30,31,32,38,40,41,],[35,35,35,35,35,35,]),'ELSE':([33,34,36,37,39,],[38,-9,40,41,-10,]),'STRING_LITERAL':([35,],[39,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'model_decl':([0,],[2,]),'input_decl':([2,],[4,]),'feature_decl':([4,],[7,]),'ident_list':([5,13,14,],[9,18,19,]),'train_decl':([7,],[11,]),'condition_decl':([11,],[15,]),'action':([30,31,32,38,40,41,],[33,36,37,42,43,44,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> model_decl input_decl feature_decl train_decl condition_decl','program',5,'p_program','parser.py',9),
  ('model_decl -> MODEL IDENTIFIER','model_decl',2,'p_model_decl','parser.py',13),
  ('input_decl -> INPUT ident_list','input_decl',2,'p_input_decl','parser.py',17),
  ('feature_decl -> FEATURE EXTRACT ident_list','feature_decl',3,'p_feature_decl','parser.py',21),
  ('train_decl -> TRAIN R_MODEL USING R_THRESHOLD NUMBER','train_decl',5,'p_train_decl','parser.py',25),
  ('condition_decl -> IF IDENTIFIER GT THRESHOLD THEN action ELSE action','condition_decl',8,'p_condition_decl','parser.py',29),
  ('condition_decl -> IF IDENTIFIER LT THRESHOLD THEN action ELSE action','condition_decl',8,'p_condition_decl','parser.py',30),
  ('condition_decl -> IF IDENTIFIER EQ THRESHOLD THEN action ELSE action','condition_decl',8,'p_condition_decl','parser.py',31),
  ('action -> ALERT','action',1,'p_action','parser.py',35),
  ('action -> LOG STRING_LITERAL','action',2,'p_action','parser.py',36),
  ('ident_list -> IDENTIFIER','ident_list',1,'p_ident_list_single','parser.py',43),
  ('ident_list -> IDENTIFIER COMMA ident_list','ident_list',3,'p_ident_list_multi','parser.py',47),
]
