# Generated by NeuroScript Compiler
import random
import statistics

class Anomaly_detectorModel:
    def __init__(self, threshold):
        self.threshold = threshold

    def extract_features(self, sound, vibration):
        print(f"Extracting features: RMS, variance...")
        # Simulating feature extraction
        RMS = random.uniform(0, 1.0)
        variance = random.uniform(0, 1.0)

        # Computing simulated anomaly score based on features
        anomaly = (RMS + variance) / 2
        return anomaly

    def run(self, sound, vibration):
        anomaly = self.extract_features(sound, vibration)
        print(f"Computed anomaly score: {anomaly:.4f} (Threshold: {self.threshold})")
        
        if anomaly > self.threshold:
            print('*** ALERT: Anomaly Detected! ***')
        else:
            print('LOG: Normal')

if __name__ == "__main__":
    detector = Anomaly_detectorModel(threshold=0.7)
    # Simulating data ingestion
    detector.run([random.random() for _ in range(10)], [random.random() for _ in range(10)])
